name: PR Open/Sync - Lint
on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: pip install uv
    - run: uv sync
    - run: make lint